export const ConstantText = {
    PASSWORD_MIN_LENGTH: 8,
    WRONG_PASSWORD: 'auth/wrong-password',
    WRONG_PASSWORD_ERR_MSG: 'Password is incorrect',
    WRONG_EMAIL: 'auth/user-not-found',
    WRONG_EMAIL_ERR_MSG: 'Email does not exist',
    TOO_MANY_REQUESTS: 'auth/too-many-requests',
    TOO_MANY_REQUESTS_ERR_MSG: 'too many false requests for this account, try again later',
    FAILED_LOGIN: 'Failed to login user!',
    FAILED_LOGIN_ERR_MSG: 'Email is not valid!',
    SHORT_PASSWORD: 'password is too short',
    EMAIL_IN_USE: 'auth/email-already-in-use',
    EMAIL_IN_USE_ERR_MSG: 'Email address is already in use',
    INVALID_EMAIL: 'auth/invalid-email',
    INVALID_EMAIL_ERR_MSG: 'Email address must be provided',
    WEAK_PASSWORD: 'auth/weak-password',
    WEAK_PASSWORD_ERR_MSG: 'Password is too weak',
    INVALID_PASSWORD_MSG: 'Passwords do not match / password length > 8',
    INVALID_EMAIL_MSG: 'Email address is not valid',
    SUCCESS: 'Success',
    SUCCESS_SIGNUP_MSG: 'Signed up!',
    SUCCESS_LOGIN_MSG: 'Logged In!',
    ERROR_ALRT: 'Error!',
    ALERT: 'Alert!',
    TERMS_N_PRIVACY_CONTENT_TEXT: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Lorem nam quis tincidunt nunc lobortis id imperdiet volutpat aliquam. Purus felis lacus, in at elit quis adipiscing urna, at. Libero risus, at ultrices metus eu quisque nibh dictum. Nunc enim feugiat mattis convallis vehicula. Mattis ullamcorper tempus, sem egestas varius dapibus tincidunt. Ullamcorper nisi eget fringilla in pellentesque urna, integer platea in. Auctor blandit tellus enim vel blandit dignissim magna dolor. Nec lorem amet risus elementum. Cursus eget sit id vitae elit non. Eleifend purus aliquam interdum leo nunc ultrices. Mattis dui nunc sed euismod quis mauris. Accumsan at nulla cras cursus sed. Pretium nunc vitae risus pulvinar augue leo nisl. Tristique ipsum imperdiet magna sit. Mattis enim tempor in varius elementum sagittis. Sit proin mi, ut id id ac nam. Dui tellus est ut purus leo id sed lectus et et.',
    TERMS_N_PRIVACY_TITLE: 'Terms & privacy',
    PROFILE_TITLE: 'My Profile',
    PROFILE_EDIT: 'Edit profile',
    PROFILE_INPUT_LABEL_NAME: 'Name',
    PROFILE_INPUT_LABEL_EMAIL: 'Email',
    NOTIFICATION_MSG: 'Notification text about a new article from a tag you liked, two lines of text.',
    TOP_HEADLINES: 'Top Headlines in USA',
    NOTIFICATIONS: 'Notifications',
    ALLOW_FILTERS_SAVE:'Alow us to save filters when entering',
    BACK_TO_APP: 'back to the app',
}

export const ConstantLabels = {
    SIGN_UP: 'Signup',
    LOGIN: 'Login',
    EMAIL: 'Your email',
    PASSWORD: 'Password',
    CONFIRM_PASSWORD: 'Re-Enter Password',
    NAVIGATE_DISPATCH: 'Navigate to dispatch',
    SORT_BY: 'Sort by',
    LOGOUT: 'Logout',
    TERMS_N_PRIVACY: 'Terms & privacy',
    SETTINGS: 'Settings',
    EDIT_PROFILE: 'Edit my profile',
    SAVED_ARTICLES: 'Saved articles',
    LAST_LOGIN: 'Last Login: ',
    GO_BACK: 'Back',
    SEARCH_RESULTS: 'Search results',
    SAVE_FILTERS: 'Save filters',
}
